codecov:
  notify:
    after_n_builds: 2

coverage:
  precision: 1
  round: down
  range: '90...100'

  status:
    project:
      default:
        target: 100
    patch: false
    changes: false

comment:
  layout: 'reach, diff, files, footer'
  behavior: new
  require_changes: true
  after_n_builds: 3

parsers:
  javascript:
    enable_partials: true
